### ISSUE TITLE
Importing Gives Wrong Account

### ISSUE THREAD

**Issue by cartony** [cderickson/MTGO-Tracker#1]
Hello.

I have played hundreds of MTGO matches on my computer. One time, however, a friend played a match on my computer on his account.

When I use the program and select the correct folders, it only pulls up one match: the match he played on my computer. My folders are set correctly. What can I do to fix this?

**Comment by cderickson** [comment]
Did your matches import correctly at any time before, or is this the first time you are trying to import files? Have you played any matches after your friend's single match? Did you re-install MTGO at any time?

It could be MTGO changing the way files are saved if you play on multiple accounts, it's not something I thought to test for. If you can .zip up the "C:\Users\[user]\AppData\Local\Apps" folder you are importing, that would help me diagnose the issue, otherwise I'll create a 2nd account and try to recreate the issue sometime this weekend.

If you want to start importing matches right away, you can try re-installing MTGO, although you would lose your past play history.

**Comment by cartony** [comment]
I've just started using the software, so never successfully imported any matches.

I have played matches since his match, yes.

I haven't reinstalled MTGO to my knowledge.

I will upload the folder and send it to you on Reddit.

**Comment by cderickson** [comment]
Cool looking forward to it. I think you can attach files to comments on here if that's easier for you.

**Comment by cderickson** [comment]
Truncated GameLog files (created due to mid-match disconnect) were causing the tool to hang during import. This has been fixed in March release by skipping truncated files.
