### ISSUE TITLE
Automaticly set up format

### ISSUE THREAD

**Issue by szkuznik** [cderickson/MTGO-Tracker#23]
Hi, I have around 800 matches played, If I understand corectly tracker gets archetype from mtgoldfish, could it also get format from there? Manually adding format to 800 matches would be a pain?

**Comment by cderickson** [comment]
Unfortunately there's not a good way to automatically add the format. That information isn't in the log file so it will at best just be a guess, and since you can play for example Modern decks in Legacy and lots of cards are played in multiple formats it will never be very accurate.

You can change the format for multiple matches by using multi-select (Shift+click) to change up to 25 or 35 matches in one operation, so it shouldn't be too bad, especially if you only play one or two formats. Getting through the backlog of matches for the first time is always the toughest part

**Comment by szkuznik** [comment]
Okay @cderickson How does this deck_data_guess works, I'm looking at the code, but I'm not sure, you are just looking at cards that the player casted during the game? There is no way to get some information about the deck?

**Comment by cderickson** [comment]
Deck names and sample decklists are scraped from MTGGoldfish tournament results monthly. The program checks the list of cards played in a match and compares it against these sample lists to guess a deck name.

There's no other deck information available in the log file, it's just like if you watched someone play a match, then have to guess what deck they're playing. If the match goes really fast (maybe you get mana-screwed or die on turn 1) then it will not be very accurate.
